### ISSUE TITLE
partial support !!

### ISSUE THREAD

**Issue by Dancopy** [tomaskovacik/arduino#16]
Not yet fully supported? Thanks

**Comment by mnaberez** [comment]
> Not yet fully supported? Thanks

Could you please give more information on what support you are requesting?  There are at least ten different projects in this repository.

**Comment by Dancopy** [comment]
First, thank you for the response.
No, no! Is that by the title (partial support for 3 displays), I found that the library had some pending.
Taking advantage of the opportunity, do you have a sketch with scrolling text in various colors?
Thank you very much

**Comment by tomaskovacik** [comment]
good morning to all :)

you are talking about this one? https://github.com/tomaskovacik/arduino/tree/master/myMatrix 

not all features of myMatrix are implemented.. I'm sorry do not remember what it mean exacty

**Comment by Dancopy** [comment]
Hi Tomáš
Yes, it's from that library itself; So, I repeat the question: do you have any sketch with multi-color scrolling for 2 or 3 modules of this? Thanks++

**Comment by tomaskovacik** [comment]
I can check  i have used it for green red buy i have to check my backups...T.On 16 Feb 2019 17:10, Dancopy <notifications@github.com> wrote:Hi Tomáš

Yes, it's from that library itself; So, I repeat the question: do you have any sketch with multi-color scrolling for 2 or 3 modules of this? Thanks++

**Comment by Dancopy** [comment]
Okay friend, I'll wait for you.
If you do not mind, I'd like to ask you something else: do you have any arduino or esp8266 sketch for this module? (https://pt.aliexpress.com/item/P4-75-dot-matrix-led-module-3-75mm-high-clear-top1-for-text-display-304-152mm/32605629557.html?spm=a2g0s.13010208.99999999.272.2e9b3c00a0sj4c)
I find nothing on the internet about it. It is with hub08 interface (Red-Green+Yellow).
Thank you very much

**Comment by tomaskovacik** [comment]
here we go, enjoy

it is something that count number of pushes of 2 buttons, and store it in eeprom, so counts are not deleted after reset 

[mec.zip](https://github.com/tomaskovacik/arduino/files/2874700/mec.zip)

**Comment by Dancopy** [comment]
Thank you tomaskovacik
Do you have any more sketches for this matrix, like colored text scrolling, for example? Thank you again

**Comment by tomaskovacik** [comment]
no nothing more, this is only one project I use it for
