### ISSUE TITLE
Question - 3LB protocol using Raspberry PI

### ISSUE THREAD

**Issue by ibanezgomez** [tomaskovacik/arduino#8]
Hi tomaskovacik, do you think is posible to implement the 3LB protocol and comunicate whit instrument cluster using a Raspberry Pi and GPIO interfaces?

Using your code I've tried this: http://pastebin.com/Qg08ZqYr

But whitout success.

What do you think? Your work is awesome!!!

Thanks, Samuel.

**Comment by tomaskovacik** [comment]
try disable ena functionaly at all and we will see

**Comment by ibanezgomez** [comment]
I'm sorry but I do not understand properly.

Should eliminate the ENA signal?

**Comment by tomaskovacik** [comment]
on my old audi, if nothing change on ENABLE line, cluster will show text for about 30seconds or so. This is standard SPI with somehow strange ENABLE line, wich can be "bidirectional".  with something line ack functionality

t.

**Comment by mnaberez** [comment]
> do you think is posible to implement the 3LB protocol and comunicate whit instrument cluster using a Raspberry Pi and GPIO interfaces?

[derpston/linux-rpi-audi-dis](https://github.com/derpston/linux-rpi-audi-dis)

**Comment by tomaskovacik** [comment]
I completely forgot about this project, I should check his code and fix arduino code if there is something wrong :)
